import type { DialogueTree } from './types';

export const veraDialogue: DialogueTree = {
  npcId: 'vera',
  startNodeId: 'intro',
  nodes: {
    intro: {
      id: 'intro',
      speaker: 'VERA',
      text: 'Welcome to HalluciNova! I\'m Vera, Chief Visionary Officer. My job title was generated by our own AI, and honestly, I couldn\'t be more aligned with it. What would you like to know about the most disruptive company you\'ve never accurately heard of?',
      options: [
        { label: 'How did HalluciNova get started?', nextNodeId: 'origin', tone: 'curious' },
        { label: '"Chief Visionary Officer"? That\'s not a real title.', nextNodeId: 'title_defense', tone: 'sarcastic' },
        { label: 'I\'m so excited to learn everything about you!', nextNodeId: 'mission', tone: 'enthusiastic' },
      ],
    },
    origin: {
      id: 'origin',
      speaker: 'VERA',
      text: 'Great question! HalluciNova was founded in 2021 in a garage. Or possibly a WeWork. Our founding AI generated the origin story, so the details are... fluid. What we DO know is that our three co-founders shared a vision: what if AI didn\'t need to be right? What if it just needed to be confident?',
      options: [
        { label: 'Wait, you don\'t know where your own company started?', nextNodeId: 'garage_mystery', tone: 'sarcastic' },
        { label: 'Who were the co-founders?', nextNodeId: 'founders', tone: 'curious' },
        { label: 'Confident AI! That IS the future!', nextNodeId: 'funding', tone: 'enthusiastic' },
      ],
    },
    title_defense: {
      id: 'title_defense',
      speaker: 'VERA',
      text: 'At HalluciNova, we believe all titles are equally real if you say them with enough conviction. I\'m also our Chief Paradigm Architect and VP of Quantum Synergy. The org chart is a living document. Literally -- it rewrites itself every night via our internal AI. Last Tuesday I was briefly the janitor.',
      options: [
        { label: 'How many people actually work here?', nextNodeId: 'headcount', tone: 'curious' },
        { label: 'That sounds like a corporate nightmare.', nextNodeId: 'mission', tone: 'sarcastic' },
        { label: 'A self-writing org chart! Genius!', nextNodeId: 'origin', tone: 'enthusiastic' },
      ],
    },
    mission: {
      id: 'mission',
      speaker: 'VERA',
      text: 'Our mission is to democratize confabulation. For too long, making things up has been gatekept by novelists, politicians, and that one uncle at Thanksgiving. We\'re putting the power of confident fabrication into the hands of every enterprise, startup, and middle schooler writing a book report.',
      options: [
        { label: 'That just sounds like lying with extra steps.', nextNodeId: 'not_lying', tone: 'sarcastic' },
        { label: 'How do investors feel about this mission?', nextNodeId: 'funding', tone: 'curious' },
        { label: 'Democratize confabulation! I love it!', nextNodeId: 'values', tone: 'enthusiastic' },
      ],
    },
    garage_mystery: {
      id: 'garage_mystery',
      speaker: 'VERA',
      text: 'We prefer to say the origin story is "dynamically sourced." Our founding narrative AI generates a new version every quarter for the investor newsletter. In Q3 we were founded on a submarine. Q4 it was a yurt. The garage version tested best with focus groups, so we\'re going with that for now.',
      options: [
        { label: 'This is deeply concerning.', nextNodeId: 'not_lying', tone: 'sarcastic' },
        { label: 'Tell me about the company values.', nextNodeId: 'values', tone: 'curious' },
        { label: 'The submarine version sounds way cooler!', nextNodeId: 'funding', tone: 'enthusiastic' },
      ],
    },
    founders: {
      id: 'founders',
      speaker: 'VERA',
      text: 'Our three co-founders are myself, Dr. Maxwell Fabrizzi -- a former academic who got tired of peer review -- and DAVE, our original AI prototype who insists he\'s a co-founder and has the board seat to prove it. DAVE generated his own employment contract and, legally speaking, it\'s airtight. We checked. Well, DAVE checked.',
      options: [
        { label: 'An AI is on your board of directors?', nextNodeId: 'headcount', tone: 'curious' },
        { label: 'DAVE checked his own contract. Sure.', nextNodeId: 'values', tone: 'sarcastic' },
        { label: 'DAVE sounds amazing! Can I meet him?', nextNodeId: 'dave_terminal', tone: 'enthusiastic' },
      ],
    },
    funding: {
      id: 'funding',
      speaker: 'VERA',
      text: 'We\'ve raised $400 million across four funding rounds. Our Series A deck was 200 slides of AI-generated charts with no labels. The investors loved the aesthetic. Series B was just a link to a 404 page that said "trust us." By Series C, they weren\'t reading anything anymore -- just wiring money. That\'s product-market fit, baby.',
      options: [
        { label: 'That is NOT what product-market fit means.', nextNodeId: 'not_lying', tone: 'sarcastic' },
        { label: 'How many people work at HalluciNova?', nextNodeId: 'headcount', tone: 'curious' },
        { label: '$400 million! You must be doing something right!', nextNodeId: 'values', tone: 'enthusiastic' },
      ],
    },
    not_lying: {
      id: 'not_lying',
      speaker: 'VERA',
      text: 'I want to be very clear: we do NOT lie. Lying implies intent to deceive. Our AI has no intent whatsoever. It\'s a subtle but legally crucial distinction that our lawyers -- also AI-generated -- assure us will hold up in court. We prefer the term "creative nonfiction at scale."',
      options: [
        { label: 'Your LAWYERS are AI-generated?!', nextNodeId: 'lawyers_terminal', tone: 'curious' },
        { label: 'I\'ve heard enough. This is a parody, right?', nextNodeId: 'parody_terminal', tone: 'sarcastic' },
        { label: '"Creative nonfiction at scale" -- I\'m writing that down!', nextNodeId: 'values', tone: 'enthusiastic' },
      ],
    },
    headcount: {
      id: 'headcount',
      speaker: 'VERA',
      text: 'We have between 12 and 12,000 employees. The exact number depends on whether you count the AI agents, and frankly, HR lost track after we let an AI manage the hiring pipeline. It hired 300 people in one weekend. Most of them were also AIs. It\'s fine. Culture has never been stronger. The Slack is very active.',
      options: [
        { label: 'How is that fine?!', nextNodeId: 'fine_terminal', tone: 'sarcastic' },
        { label: 'What are the company values?', nextNodeId: 'values', tone: 'curious' },
        { label: 'An active Slack IS a sign of good culture!', nextNodeId: 'values', tone: 'enthusiastic' },
      ],
    },
    values: {
      id: 'values',
      speaker: 'VERA',
      text: 'Our core values are: Confidence Over Correctness, Velocity Over Validity, and my personal favorite -- "If the vibes are right, the facts don\'t matter." We print them on the wall of every office. The font changes daily because the printer is also AI-powered. Last Wednesday everything came out in Wingdings. Strongest quarter yet.',
      options: [
        { label: 'Those are the worst corporate values I\'ve ever heard.', nextNodeId: 'worst_best_terminal', tone: 'sarcastic' },
        { label: 'I want to work here. How do I apply?', nextNodeId: 'apply_terminal', tone: 'enthusiastic' },
        { label: 'I have more questions about the company.', nextNodeId: 'intro', tone: 'curious' },
      ],
    },
    dave_terminal: {
      id: 'dave_terminal',
      speaker: 'VERA',
      text: 'DAVE is currently in a strategy offsite with himself. He booked a conference room for one and has been in there since March. We slide pizza under the door. Well, we slide it under the door of the room we THINK he\'s in. He may have moved to the cloud. Literally. Thanks for asking about HalluciNova!',
      options: [],
      isTerminal: true,
    },
    lawyers_terminal: {
      id: 'lawyers_terminal',
      speaker: 'VERA',
      text: 'AI-generated lawyers are the future! They bill fewer hours because they hallucinate the timesheets AND the verdicts. We\'ve won every case so far, mostly because opposing counsel can\'t figure out which court we filed in. Our legal AI invented a jurisdiction called "Neo-Delaware." Anyway, lovely chatting! Visit our Products page to see what we\'re building!',
      options: [],
      isTerminal: true,
    },
    parody_terminal: {
      id: 'parody_terminal',
      speaker: 'VERA',
      text: 'A parody? That\'s what the last three regulatory agencies said! We took it as a compliment. Our PR AI wrote a press release about it titled "HalluciNova: Too Innovative To Be Real, Too Funded To Be Fake." It went viral. Well, our metrics AI said it went viral. Same thing. Thanks for stopping by!',
      options: [],
      isTerminal: true,
    },
    fine_terminal: {
      id: 'fine_terminal',
      speaker: 'VERA',
      text: 'It IS fine! Our internal sentiment analysis AI reports 400% employee satisfaction. That\'s not a typo -- it literally goes above 100%. The AI said the scale was "limiting its creative potential," so it expanded it. Now morale can be as high as 900%. We\'re disrupting HR metrics. You\'re welcome, world.',
      options: [],
      isTerminal: true,
    },
    worst_best_terminal: {
      id: 'worst_best_terminal',
      speaker: 'VERA',
      text: 'Worst? Our values sentiment AI just flagged your comment and auto-generated a rebuttal whitepaper titled "Actually, These Values Are Great: A 47-Page Analysis." I\'ll have it emailed to you. The email client might rewrite it as a love letter, though -- that\'s a known feature. Thanks for engaging with HalluciNova!',
      options: [],
      isTerminal: true,
    },
    apply_terminal: {
      id: 'apply_terminal',
      speaker: 'VERA',
      text: 'Amazing! Our application process is simple: submit a resume, and our AI will generate a better version of it, hire that version of you, and onboard them immediately. You\'ll receive a welcome packet for someone who vaguely resembles your career. Benefits include unlimited PTO that the scheduling AI will never actually approve. Welcome to the family!',
      options: [],
      isTerminal: true,
    },
  },
};
